import { Header, RestaurantNavBar, Menu } from '../../components'

export const metadata = {
  title: 'Menu | OpenBooking',
  description: 'Generated by OpenBooking',
}

export default function RestaurantMenu() {
  return (
    <>
      <Header />
      <div className='flex m-auto w-full md:w-2/3 justify-between items-start mt-0 md:-mt-11'>
        <div className='bg-white w-[100%] rounded p-3 shadow'>
          <RestaurantNavBar />
          <Menu />
        </div>
      </div>
    </>
  )
}
