import { PrismaClient } from '@prisma/client'
import { Header, RestaurantNavBar, Menu } from '../../components'

export const metadata = {
  title: 'Menu | OpenBooking',
  description: 'Generated by OpenBooking',
}

const prisma = new PrismaClient()

const fetchRestaurantMenu = async (slug: string) => {
  const restaurant = await prisma.restaurant.findUnique({
    where: {
      slug,
    },
    select: {
      items: true,
    },
  })
  if (!restaurant) {
    throw new Error()
  }
  return restaurant.items
}

export default async function RestaurantMenu({
  params,
}: {
  params: { slug: string }
}) {
  const menu = await fetchRestaurantMenu(params.slug)

  return (
    <>
      <Header slug={params.slug} />
      <div className='flex m-auto w-full md:w-2/3 justify-between items-start mt-0 md:-mt-11'>
        <div className='bg-white w-[100%] rounded p-3 shadow'>
          <RestaurantNavBar slug={params.slug} />
          <Menu menu={menu} />
        </div>
      </div>
    </>
  )
}
