import Form from './components/Form'
import Header from './components/Header'

export const metadata = {
  title: 'Reserve | OpenBooking',
  description: 'Generated by OpenBooking',
}

export default function Reserve() {
  return (
    <>
      <div className='border-t h-screen'>
        <div className='py-5 md:py-9 w-full md:w-3/5 md:mx-auto px-1'>
          <Header />
          <Form />
        </div>
      </div>
    </>
  )
}
