import './globals.css'
import NavBar from './components/NavBar'

export const metadata = {
  title: 'OpenBooking',
  description: 'Generated by OpenBooking',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body>
        <div className='bg-gray-100 min-h-screen w-screen'>
          <div className='max-w-[100rem] m-auto bg-white'>
            <NavBar />
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
