import { Location, Review } from '@prisma/client'
import { notFound } from 'next/navigation'
import {
  Header,
  RestaurantNavBar,
  Title,
  Rating,
  Description,
  Images,
  Reviews,
  ReservationCard,
} from '../components'
import prisma from '@/lib/prismadb'

export const metadata = {
  title: 'Restaurant | OpenBooking',
  description: 'Generated by OpenBooking',
}

interface Restaurant {
  id: number
  name: string
  images: string[]
  description: string
  slug: string
  location: Location
  reviews: Review[]
}

const fetchRestaurantBySlug = async (slug: string): Promise<Restaurant> => {
  const restaurant = await prisma.restaurant.findUnique({
    where: {
      slug,
    },
    select: {
      id: true,
      name: true,
      images: true,
      description: true,
      slug: true,
      location: true,
      reviews: true,
    },
  })

  if (!restaurant) {
    notFound()
  }

  return restaurant
}

export default async function RestaurantDetails({
  params,
}: {
  params: { slug: string }
}) {
  const restaurant = await fetchRestaurantBySlug(params.slug)

  return (
    <>
      <Header slug={restaurant.slug} />
      <div className='flex flex-col md:flex-row m-auto w-full md:w-2/3 justify-start md:justify-between items-start mt-0 md:-mt-11'>
        <div className='bg-white w-full md:w-[70%] rounded p-3 shadow'>
          <RestaurantNavBar slug={restaurant.slug} />
          <Title name={restaurant.name} />
          <Rating reviews={restaurant.reviews} />
          <Description description={restaurant.description} />
          <Images images={restaurant.images} />
          <Reviews reviews={restaurant.reviews} />
        </div>
        <div className='hidden md:flex md:w-[27%] relative text-reg'>
          <ReservationCard />
        </div>
      </div>
    </>
  )
}
