import {
  Header,
  RestaurantNavBar,
  Title,
  Rating,
  Description,
  Images,
  Reviews,
  ReservationCard,
} from '../components'

export const metadata = {
  title: 'Restaurant | OpenBooking',
  description: 'Generated by OpenBooking',
}

export default function RestaurantDetails() {
  return (
    <>
      <Header />
      <div className='flex flex-col md:flex-row m-auto w-full md:w-2/3 justify-start md:justify-between items-start mt-0 md:-mt-11'>
        <div className='bg-white w-full md:w-[70%] rounded p-3 shadow'>
          <RestaurantNavBar />
          <Title />
          <Rating />
          <Description />
          <Images />
          <Reviews />
        </div>
        <div className='hidden md:flex md:w-[27%] relative text-reg'>
          <ReservationCard />
        </div>
      </div>
    </>
  )
}
